<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_login</name>
   <tag></tag>
   <elementGuidId>c8e6a9b7-5792-4584-a959-bd319e9bf65b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/section[1]/div[1]/div[1]/div[2]/form[1]/div[4]/div[1]/button[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
