<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_password</name>
   <tag></tag>
   <elementGuidId>fe0dc7ae-35e8-4d2e-b98a-2b76e67f9c17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/section[1]/div[1]/div[1]/div[2]/form[1]/div[3]/div[1]/input[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
