<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nav_login</name>
   <tag></tag>
   <elementGuidId>aec26b46-e80c-4ac0-b28e-100c5489918e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/nav[1]/ul[1]/li[3]/a[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
